from setuptools import setup, find_packages

setup(
    name="zynx_agi",
    version="0.1.0",
    packages=find_packages(),
    install_requires=[
        "fastapi>=0.68.0",
        "uvicorn>=0.15.0",
        "pydantic>=1.8.0",
        "python-jose[cryptography]>=3.3.0",
        "passlib[bcrypt]>=1.7.4",
        "python-multipart>=0.0.5",
        "requests>=2.26.0",
        "python-dotenv>=0.19.0",
        "sqlalchemy>=1.4.23",
        "alembic>=1.7.1",
        "psycopg2-binary>=2.9.1",
        "pytest>=6.2.5",
        "pytest-asyncio>=0.15.1",
        "aiohttp>=3.8.1",
        "beautifulsoup4>=4.9.3",
        "lxml>=4.6.3",
        "nltk>=3.6.3",
        "spacy>=3.1.3",
        "transformers>=4.11.3",
        "torch>=1.9.0",
        "numpy>=1.21.2",
        "pandas>=1.3.3",
        "scikit-learn>=0.24.2",
        "matplotlib>=3.4.3",
        "seaborn>=0.11.2",
        "jupyter>=1.0.0",
        "ipykernel>=6.0.3",
        "tqdm>=4.62.3",
        "pyyaml>=5.4.1",
        "pyjwt>=2.3.0",
        "httpx>=0.23.0",
        "cryptography>=3.4.7"
    ],
    extras_require={
        "dev": [
            "pytest>=6.2.5",
            "pytest-asyncio>=0.15.1",
            "pytest-cov>=2.12.1",
            "black>=21.7b0",
            "isort>=5.9.3",
            "flake8>=3.9.2",
            "mypy>=0.910"
        ]
    },
    python_requires=">=3.8",
    author="ZynxAGI Team",
    author_email="your.email@example.com",
    description="Thai Cultural Intelligence Platform",
    long_description=open("README.md").read(),
    long_description_content_type="text/markdown",
    url="https://github.com/yourusername/zynx-agi",
    classifiers=[
        "Development Status :: 3 - Alpha",
        "Intended Audience :: Developers",
        "License :: OSI Approved :: MIT License",
        "Programming Language :: Python :: 3",
        "Programming Language :: Python :: 3.8",
        "Programming Language :: Python :: 3.9",
        "Programming Language :: Python :: 3.10",
    ],
) 